# Generated by Django 5.1.7 on 2025-03-27 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=60)),
                ('Phone_no', models.IntegerField()),
                ('Country', models.CharField(max_length=40)),
                ('Amount', models.IntegerField()),
                ('State', models.CharField(max_length=40)),
                ('City', models.CharField(max_length=25)),
                ('Gender', models.CharField(max_length=10)),
            ],
        ),
    ]
