# Generated by Django 5.1.7 on 2025-04-02 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_doners_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doners',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='Phone_no',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='doners',
            old_name='State',
            new_name='state',
        ),
    ]
