# Generated by Django 5.1.7 on 2025-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_address_doners_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doners',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
