# Generated by Django 5.1.7 on 2025-04-04 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_doners_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='doners',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
    ]
