# Generated by Django 5.1.7 on 2025-12-29 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doners_pincode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('message', 'Message')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='app.doners')),
            ],
        ),
    ]
